import { Car, TrendingUp } from "lucide-react";

const vehicles = [
  {
    name: "Toyota Innova Crysta",
    trips: 48,
    earning: "₹86,400",
  },

  {
    name: "Mahindra Scorpio N",
    trips: 34,
    earning: "₹72,000",
  },

  {
    name: "Maruti Ertiga",
    trips: 29,
    earning: "₹43,500",
  },
];

function VehiclePerformance() {
  return (
    <section
      className="
rounded-2xl
border
border-slate-200
bg-white
p-6
shadow-sm
"
    >
      <div className="mb-5">
        <h2
          className="
text-xl
font-extrabold
"
        >
          Vehicle Performance
        </h2>

        <p
          className="
text-sm
text-slate-500
mt-1
"
        >
          Revenue generated by each vehicle.
        </p>
      </div>

      <div className="space-y-4">
        {vehicles.map((vehicle) => (
          <div
            key={vehicle.name}
            className="
rounded-xl
bg-slate-50
p-4
flex
items-center
justify-between
"
          >
            <div className="flex items-center gap-3">
              <div
                className="
h-10
w-10
rounded-xl
bg-blue-50
text-blue-600
flex
items-center
justify-center
"
              >
                <Car size={20} />
              </div>

              <div>
                <p className="font-bold text-slate-800">{vehicle.name}</p>

                <p className="text-xs text-slate-400">
                  {vehicle.trips} completed trips
                </p>
              </div>
            </div>

            <div className="text-right">
              <div
                className="
flex
items-center
gap-1
justify-end
text-emerald-600
"
              >
                <TrendingUp size={14} />

                <span className="text-xs font-bold">Top Performer</span>
              </div>

              <p className="font-extrabold">{vehicle.earning}</p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

export default VehiclePerformance;
